[allowlist]
  description = "Allowlist"
  paths = [
    '''src/https''',
  ]
  files = [
    '''*.crt''',
    '''*.key''',
    '''secret''',
    '''ca.key''',
    '''user2.key''',
    '''user1.key''',
    '''*.csr''',
  ]
