title:            LEo的网络日志
description:      LEo's Blog
url:              http://reborncodinglife.com
signoff:          LEo


links:
  - name:         about
    url:          /about
  - name:         blog
    url:          http://reborncodinglife.com
    external:     true
  - name:         gitHub
    url:          http://github.com/songleo
    external:     true
highlighter:      rouge
permalink:        pretty
markdown:         kramdown
redcarpet:
  extensions:
    - smart