title:            Reborn Coding Life
description:      LEo's Blog
url:              http://reborncodinglife.com
signoff:          LEo
#disqus_shortname: #reborncodinglife# disqus comment thread for post header options. ( leave blank if unwanted. )
#facebook_appid:   true# appid for like button, remove from /_includes/share.html if unwanted.
#google_analytics: true# set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          http://reborncodinglife.com/about
  - name:         Blog
    url:          http://reborncodinglife.com
    external:     true
  - name:         GitHub
    url:          http://github.com/songleo
    external:     true
highlighter:      rouge
permalink:        pretty
markdown:         kramdown
redcarpet:
  extensions:
    - smart
